version: '3.8'
services:
  runner:
    build: .
    image: ci-runner-api
    ports:
      - "8080:8080"
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ci_user
      - DB_PASSWORD=ci_pass
      - DB_NAME=ci_jobs
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ci_user
      POSTGRES_PASSWORD: ci_pass
      POSTGRES_DB: ci_jobs
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: